
services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: xuanbinh1234
      MYSQL_DATABASE: cellphones_demo
    ports:
      - "8013:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=cellphones
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cellphones_demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=xuanbinh1234
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - CELLPHONES_JWTSECRET=cellphonesssecretiscellphonesssecretiscellphonesssecretis
      - CELLPHONES_JWTEXPIRATIONMS=84600000
      - CELLPHONES_JWTREFRESHEXPIRATIONMS=846000000
      - CLOUDINARY_CLOUD_NAME=daubnjjos
      - CLOUDINARY_API_KEY=542363842418154
      - CLOUDINARY_API_SECRET=65CJdPRH30ondmjWKhI6j9PBWOE
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
